# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.runs/dcm_25m_synth_1/dcm_25m.dcp
set_property used_in_implementation false [get_files C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.runs/dcm_25m_synth_1/dcm_25m.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/imports/sources/vga_timing.v
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/imports/sources/debounce.v
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/new/keyboard.v
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/imports/sources/top_flyinglogo.v
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/imports/new/x7seg.v
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/imports/new/modcnt.v
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/imports/new/count_time.v
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/new/game.v
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/imports/new/clock_top.v
  C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/sources_1/new/top_soccer.v
}
read_xdc C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/constrs_1/new/xdc_.xdc
set_property used_in_implementation false [get_files C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/constrs_1/new/xdc_.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.cache/wt [current_project]
set_property parent.project_dir C:/Users/Lenovo/Desktop/linangame7/linan_game [current_project]
catch { write_hwdef -file top_soccer.hwdef }
synth_design -top top_soccer -part xc7a100tcsg324-1
write_checkpoint top_soccer.dcp
report_utilization -file top_soccer_utilization_synth.rpt -pb top_soccer_utilization_synth.pb
