set_property SRC_FILE_INFO {cfile:C:/Users/Lenovo/Desktop/linangame7/linan_game/project_2.srcs/constrs_1/new/xdc_.xdc rfile:../../../project_2.srcs/constrs_1/new/xdc_.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports sign]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports sign]
