set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN D8 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN D7 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN C7 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN B7 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN A6 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN B6 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN A5 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN C6 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN A4 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN C5 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN B4 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN A3 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN B11 [get_ports hsync]
set_property PACKAGE_PIN B12 [get_ports vsync]
set_property PACKAGE_PIN R6 [get_ports rst]

set_property PACKAGE_PIN U9 [get_ports rst1]
set_property IOSTANDARD LVCMOS33 [get_ports rst1]


set_property PACKAGE_PIN R7 [get_ports clrn]
set_property IOSTANDARD LVCMOS33 [get_ports clrn]
set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property PULLUP true [get_ports ps2_clk]
set_property PULLUP true [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]

set_property IOSTANDARD LVCMOS33 [get_ports down1]
set_property IOSTANDARD LVCMOS33 [get_ports left1]
set_property PACKAGE_PIN T16 [get_ports left1]
set_property PACKAGE_PIN V10 [get_ports down1]
set_property PACKAGE_PIN R10 [get_ports right1]
set_property IOSTANDARD LVCMOS33 [get_ports right1]
set_property PACKAGE_PIN F15 [get_ports up1]
set_property IOSTANDARD LVCMOS33 [get_ports up1]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN L3 [get_ports {a_to_g[6]}]
set_property PACKAGE_PIN N1 [get_ports {a_to_g[5]}]
set_property PACKAGE_PIN L6 [get_ports {a_to_g[0]}]
set_property PACKAGE_PIN N4 [get_ports {an[5]}]
set_property PACKAGE_PIN N2 [get_ports {an[4]}]
set_property PACKAGE_PIN N5 [get_ports {an[3]}]
set_property PACKAGE_PIN M3 [get_ports {an[2]}]
set_property PACKAGE_PIN M6 [get_ports {an[1]}]
set_property PACKAGE_PIN N6 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clr]
set_property PACKAGE_PIN P4 [get_ports clr]
set_property PACKAGE_PIN M4 [get_ports dp]
set_property PACKAGE_PIN P3 [get_ports init]
set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property IOSTANDARD LVCMOS33 [get_ports init]

set_property PACKAGE_PIN L5 [get_ports {a_to_g[4]}]
set_property PACKAGE_PIN L4 [get_ports {a_to_g[3]}]
set_property PACKAGE_PIN K3 [get_ports {a_to_g[2]}]
set_property PACKAGE_PIN M2 [get_ports {a_to_g[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports time_flag]
set_property PACKAGE_PIN T8 [get_ports time_flag]


set_property PACKAGE_PIN V9 [get_ports sign]
set_property IOSTANDARD LVCMOS33 [get_ports sign]

set_property PACKAGE_PIN P5 [get_ports {sorceb[0]}]
set_property PACKAGE_PIN U1 [get_ports {sorceb[1]}]
set_property PACKAGE_PIN R2 [get_ports {sorceb[2]}]
set_property PACKAGE_PIN P2 [get_ports {sorceb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sorceb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sorceb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sorceb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sorceb[0]}]
set_property PACKAGE_PIN U6 [get_ports {sorceg[0]}]
set_property PACKAGE_PIN V4 [get_ports {sorceg[1]}]
set_property PACKAGE_PIN U3 [get_ports {sorceg[2]}]
set_property PACKAGE_PIN V1 [get_ports {sorceg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sorceg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sorceg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sorceg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sorceg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports init_sorce]
set_property PACKAGE_PIN U8 [get_ports init_sorce]

set_property PACKAGE_PIN V9 [get_ports sorce_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sorce_clk]

set_property PACKAGE_PIN L1 [get_ports {an[6]}]
set_property PACKAGE_PIN M1 [get_ports {an[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[6]}]
